language: ruby
bundler_args: --without development
script: bundle exec rake spec jasmine:ci

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - "export DISPLAY=:99.0"
  - "export JASMINE_BROWSER=firefox"

before_script:
  - psql -c 'create database nineteen_wu_test;' -U postgres
  - "sed 's/username: nineteen_wu/username: postgres/' config/database.yml.example > config/database.yml"

rvm:
  - 1.9.3
  - 1.9.2
  - ree
  - ruby-head
  - jruby-head
