# http://about.travis-ci.org/docs/user/build-configuration/
language: ruby

bundler_args: --without production development --path=~/.bundle

script: bundle exec rake travis:script

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - "export DISPLAY=:99.0"
  - "export JASMINE_BROWSER=firefox"
  - "firefox --version"
  - "cat /etc/timezone"
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
  - gem install bundler fog
  - "./script/travis/bundle_install.sh"

before_script:
  - "bundle exec rake travis:before_script"

after_script: "ruby script/travis/bundle_cache.rb"

env:
  global:
    - BUNDLE_ARCHIVE="19wu"
    - AWS_S3_BUCKET="19wu"
    - secure: "EcbipPYfZxMS62cfroLKM7MGaShkuUH6Me2jMB/l9OhlD2gRUzXR9bQZx+1I\nGQMtk1v6D8KH2shR+8h6iKJzbD09mh8fDNBOBlLX2dlbCE1ZYJ2rYRFiCbcd\nSbcdP/xN+kOKo1Fe/eVCuQRTVYqHmMpwSSQA3Cbxv8pR31TCjNU="
  matrix:
    - DATABASE=pg
    - DATABASE=mysql2
    - DATABASE=sqlite3

rvm:
  #- 1.9.3
  - 2.0.0
  #- ruby-head    # will cause timeout
